


CREATE TABLE IF NOT EXISTS Salesman (
    SID INT PRIMARY KEY,
    SNAME VARCHAR(20) NOT NULL,
    LOCATION VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    PRODID INT PRIMARY KEY,
    PDESC VARCHAR(28) NOT NULL,
    PRICE VARCHAR(45) NOT NULL,
    CATEGORY VARCHAR(23) NOT NULL,
    DISCOUNT DECIMAL(4, 2)
);

DESC PRODUCT;

ALTER TABLE product MODIFY PDESC VARCHAR(30); -- it will drop NOT NULL and also change the size to 30

CREATE TABLE IF NOT EXISTS SALE (
    SALEID INT PRIMARY KEY,
    SID INT,
    SLDATE DATE,
    AMOUNT DECIMAL(9,2),
    CONSTRAINT sale_sid_fk FOREIGN KEY (SID) REFERENCES Salesman (SID) 
);

CREATE TABLE IF NOT EXISTS SALEDETAIL (
    SALEID INT,
    PRODID INT,
    QUANTITY INTEGER,
    CONSTRAINT saled_pk PRIMARY KEY (SALEID, PRODID),
    CONSTRAINT saled_prid_fk FOREIGN KEY (PRODID) REFERENCES PRODUCT (PRODID),
    CONSTRAINT saled_slid_fk FOREIGN KEY (SALEID) REFERENCES SALE (SALEID)
);

